
services:
  art-desing-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: art_desing_app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "9093:9093"  # Проброс порта

networks:
  app_network:
    driver: bridge
